# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: Excelsis.ExcelsisHelper
PackageVersion: 1.4.28
InstallerType: nullsoft
Scope: machine
ElevationRequirement: elevationRequired
UpgradeBehavior: install
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/simonsystem609/ExcelsisHelper/releases/download/excelsis-helper-v1.4.28/ExcelsisHelper-1.4.28-Setup.exe
    InstallerSha256: A4057B20063C3AFFC1EC2E0A0E8A17132A7C8F8B203A72B1F26F61ADECC2A6C3
ManifestType: installer
ManifestVersion: 1.10.0
