# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: Excelsis.ExcelsisView
PackageVersion: 1.1.36
InstallerType: nullsoft
Scope: machine
ElevationRequirement: elevationRequired
UpgradeBehavior: install
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/simonsystem609/ExcelsisViewer/releases/download/excelsis-view-v1.1.36/ExcelsisView-Setup-1.1.36.exe
    InstallerSha256: 8164ECD02A55B3443A7699989DC0E476B405CD1BD5D2F1DC1E6FC2349BA704EF
ManifestType: installer
ManifestVersion: 1.10.0
